version: '3.4'

services:
  greenflux:
    image: greenflux
    build:
      context: .
      dockerfile: src/GreenFlux.Charging.Service/Dockerfile
    depends_on:
      - sqldb
      - redis

  sqldb:
    image: "mcr.microsoft.com/mssql/server"
    volumes: 
      - sql-data:/sql-data
    environment:
        SA_PASSWORD: "P@ssw0rd"
        ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"

  redis:
    image: redis:6.2-alpine
    volumes: 
      - redis-data:/redis-data
    ports:
      - '6379:6379'

volumes:
    sql-data:
    redis-data: